name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
     
      uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
      with:
        path: dist/my-demo-app  
        build_command: ng build --base-href https://hyperhexsolutions.com 
                

