name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "hyperhex-admin"
          git config --global user.email "hyperadmin@hyperhexsolutions.com"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 
      
      - name: Install dependencies
        run: npm install -g @angular/cli
      
      - name: Install dependencies
        run: npm i 

      - name: Install GHPAGES
        run: ng add angular-cli-ghpages@latest --skip-confirmation

      - name: Build the application
        run: ng build --base-href https://hyperhexsolutions.com

      - name: Add CNAME file
        run: echo "hyperhexsolutions.com" >> dist/my-demo-app/CNAME
      
      - name: node version
        run: node -v
      
      - name: Deploy to GitHub Pages 
        run: npx ngh --no-silent --dir=dist/my-demo-app 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

