name: Build and test

on:
  push:
    branches: [release]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.15.0

      - name: Prepare
        run: |
          cd src
          npm install
          npm run build
          npm run test
          cd dist
          npm link
          cd ..
          cd ..
          npm install -g @angular/cli
          ng new hyperhex.github.io --defaults
          cd hyperhex.github.io
          npm link angular-cli-ghpages
          ng add angular-cli-ghpages

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.DGITHUB_TOKEN }}
        run: |
          cd hyperhex.github.io
          ng deploy --name="The Buildbot" --email="buildbot@angular2buch.de" --cname=angular-cli-ghpages.angular.schule